# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # make vm nfs server role
  config.vm.define "nfs" do |node|
    node.vm.box = "centos/7"
    node.vm.box_check_update = false
    # node.vbguest.auto_update = false
    node.vm.hostname = "nfs"
    node.vm.network "private_network", ip: "172.16.10.106"
    node.vm.provision "shell", path: "setup-nfs.sh"   
  end

end
