# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # make vm test
  config.vm.define "test" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    node.vm.hostname = "test"
    node.vm.network "private_network", ip: "172.16.10.108"
  end

end
